apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pihole
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: pihole
subjects:
- kind: ServiceAccount
  name: pihole-sa
  namespace: pihole
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
