---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/k8s/pihole-pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Must match the PV size

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 53
        env:
        - name: TZ
          value: "America/New_York"  # Adjust time zone as necessary
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: WEBPASSWORD
        volumeMounts:
        - mountPath: /etc/pihole/
          name: pihole-volume
      volumes:
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 8181
    targetPort: 80
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: pihole
