pipeline {
    agent any

    environment {
        KUBECONFIG_CREDENTIALS = '8bfe3e4a-62c9-4305-a5e2-4d4debb8242b' // The correct Secret file ID for kubeconfig
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the latest code from the repo
                git branch: 'main', url: 'https://github.com/sohaib1khan/kubernetes_craft.git'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Use Kubeconfig credentials as a Secret file
                    withCredentials([file(credentialsId: "${KUBECONFIG_CREDENTIALS}", variable: 'KUBECONFIG')]) {
                        sh 'kubectl apply -f Skaffold_Deployments/nginx_app_test/k8s/'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
