apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: nginx-app-k8s
deploy:
  kubectl:
    manifests:
      - ./k8s/nginx-deployment.yaml
    flags:
      apply:
        - --namespace=nginx-app
