#!/bin/bash

# Create Dockerfile
cat <<EOF > Dockerfile
# Use the latest Ubuntu image
FROM ubuntu:latest

# Set non-interactive mode (this prevents some prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Update the system and install required packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    vim \
    less \
    && rm -rf /var/lib/apt/lists/*

# Install Python libraries using pip
RUN pip3 install openai python-dotenv requests


# Install bard api 
RUN pip3 install bardapi
RUN pip install bardapi python-dotenv
RUN pip install bardapi --upgrade

# Copy local script and .env to the container
COPY ./chatbot/chatbot.py /home/
COPY ./chatbot/.env /home/

# Set the working directory
WORKDIR /app

# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]
EOF

# Create docker-compose.yml
cat <<EOF > docker-compose.yml
version: '3'

services:
  my-python-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_python
    container_name: python_container
    volumes:
      - ./:/home
    working_dir: /home
EOF

echo "Dockerfile and docker-compose.yml have been created in the current directory."


