---
apiVersion: v1
kind: Namespace
metadata:
  name: chatbot-namespace

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot-pv
  namespace: chatbot-namespace
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath: # Using hostPath for demonstration purposes; consider using a more robust storage solution for production
    path: "/home/k8s/pv" # Change this to a valid path on your host

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-pvc
  namespace: chatbot-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: chatbot-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot-container
        image: bluedreamz/chatbot-image
        volumeMounts: # Mount the PVC to your desired path in the container
        - mountPath: "/home/k8s/pv"
          name: chatbot-volume
      volumes:
      - name: chatbot-volume
        persistentVolumeClaim:
          claimName: chatbot-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot-namespace
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 5000
  type: LoadBalancer
